### ISSUE TITLE
[BUG] package_manager_impl.is_available() produces false negatives

### ISSUE THREAD

**Issue by mborejdo** [tversteeg/emplace#105]
**Describe the bug**
I am using emplace on Windows 10 currently. I want to manage npm, scoop and cargo packages.
Currently emplace does not recognize these managers, because `is_available` returns always false. I narrowed it down to `is_executable` returning false, when the commands-Vector does not include ".exe". For scoop there does not seem to be an executable in PATH (just a cmd file). `is_executable` does not seem to return true here neither.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Shell: nushell (same in cmd)

**Comment by tversteeg** [comment]
It should be fixed now, could you verify if it works?

**Comment by mborejdo** [comment]
I can verify that npm and cargo installations work now. Thanks :+1: 
For me scoop still is not working as expected.  
`which scoop` shows `C:\Users\user\scoop\shims\scoop.cmd`

**Comment by tversteeg** [comment]
I did not know that `.cmd` also had to be supported, added it now. Does it work?

**Comment by mborejdo** [comment]
Hmm.. Still no luck.
executing `is_executable("C:\Users\user\scoop\shims\scoop.cmd");` directly also results in false.
```
println!("{}", is_executable("C:\\Users\\user\\scoop\\shims\\scoop.cmd")); //false
println!("{}", is_executable("C:\\Users\\user\\.tools\\bin\\cargo.exe")); //true
```

**Comment by tversteeg** [comment]
This seems to be an issue with the [`is_executable`](https://github.com/fitzgen/is_executable) crate. I'll remove it in favor of checking if the file exists.

**Comment by tversteeg** [comment]
I pushed another change, does it work now?

**Comment by mborejdo** [comment]
Yay, we went a bit further. I am being prompted to install my scoop package now. Thats great.
Unfortunately we continue with `[ERROR] "sudo scoop install ffmpeg"` 
Should i open another issue, as the actual problem is solved now?

**Comment by tversteeg** [comment]
Yes another issue would be nice.
